name: habit_app
description: A new Flutter project.

publish_to: 'none'

version: 1.1.1+4

environment:
  sdk: '>=3.6.0 <4.0.0'

dependencies:
  animated_flip_counter: ^0.2.5
  cloud_firestore: ^5.6.3
  confetti: ^0.8.0
  cupertino_icons: ^1.0.2
  fake_cloud_firestore: ^3.1.0
  firebase_auth: ^5.4.2
  firebase_auth_mocks: ^0.14.1
  firebase_core: ^3.11.0
  flutter:
    sdk: flutter
  flutter_app_badger: ^1.5.0
  flutter_bounce: ^1.1.0
  flutter_dotenv: ^5.2.1
  flutter_launcher_icons: ^0.13.1
  flutter_local_notifications: ^17.2.4
  flutter_native_splash: ^2.3.2
  flutter_riverpod: ^2.1.3
  fpdart: ^1.1.0
  freezed_annotation: ^2.0.3
  google_generative_ai: ^0.4.6
  home_widget: ^0.7.0
  intl: ^0.18.0
  logger: ^2.5.0
  mockito: ^5.4.4
  riverpod_annotation: ^2.5.3
  riverpod_lint: ^2.1.0
  shared_preferences: ^2.3.2
  timezone: ^0.9.4
  very_good_analysis: ^7.0.0
  vibration: ^2.0.1
  webview_flutter: ^4.10.0
  workmanager: ^0.5.2
  
flutter_native_splash:
  image: images/habister_icon.png
  color: "FFFFFF"

dependency_overrides:
  analyzer: ^6.3.0
  custom_lint_core: ^0.6.6

dev_dependencies:
  build_runner: ^2.4.6
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.4.2
  json_serializable: ^6.7.1
  riverpod_generator: ^2.4.0
  
flutter_icons:       
  android: true
  ios: true
  image_path: "images/icon.png"
  
flutter:

  uses-material-design: true

  assets:
    - images/
    - .env

  fonts:
    - family: KosugiMaru
      fonts:
        - asset: fonts/KosugiMaru-Regular.ttf
  