name: habit_app
description: A new Flutter project.

publish_to: 'none'

version: 1.1.1+4

environment:
  sdk: '>=3.6.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  intl: ^0.18.0
  home_widget: ^0.7.0
  workmanager: ^0.5.2
  animated_flip_counter: ^0.2.5
  flutter_bounce: ^1.1.0
  flutter_native_splash: ^2.3.2
  fpdart: ^1.1.0
  riverpod_lint: ^2.1.0
  firebase_core: ^2.15.1
  firebase_auth: ^4.9.0
  flutter_riverpod: ^2.1.3
  freezed_annotation: ^2.0.3
  cloud_firestore: ^4.9.2
  flutter_launcher_icons: ^0.13.1
  riverpod_annotation: ^2.5.3
  fake_cloud_firestore: ^2.5.2
  firebase_auth_mocks: ^0.13.0
  shared_preferences: ^2.3.2
  flutter_local_notifications: ^17.2.4
  mockito: ^5.4.4
  timezone: ^0.9.4
  flutter_app_badger: ^1.5.0
  confetti: ^0.8.0
  vibration: ^2.0.1
  webview_flutter: ^4.10.0
  very_good_analysis: ^7.0.0
flutter_native_splash:
  image: images/habister_icon.png
  color: "FFFFFF"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  freezed: ^2.4.2
  json_serializable: ^6.7.1
  riverpod_generator: ^2.4.0
  
flutter_icons:       
  android: true
  ios: true
  image_path: "images/icon.png"
  
flutter:

  uses-material-design: true

  assets:
    - images/

  fonts:
    - family: KosugiMaru
      fonts:
        - asset: fonts/KosugiMaru-Regular.ttf
  