// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBa6PVQTnFH-_tYVcQhAtagGCLPD5miQGI',
    appId: '1:1096135969859:web:fcb550c220af01dc2ed8f6',
    messagingSenderId: '1096135969859',
    projectId: 'habister-dev',
    authDomain: 'habister-dev.firebaseapp.com',
    storageBucket: 'habister-dev.firebasestorage.app',
    measurementId: 'G-75P37BMPPV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGwdtv_YjmeYtIgpkFJA14uSNGMOu3dXc',
    appId: '1:1096135969859:android:3fb6e65b6baeb20e2ed8f6',
    messagingSenderId: '1096135969859',
    projectId: 'habister-dev',
    storageBucket: 'habister-dev.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0vdigZEk3-mNj5-g6dk9DW-Xqk1_8R_c',
    appId: '1:1096135969859:ios:30575b22fb67ff3b2ed8f6',
    messagingSenderId: '1096135969859',
    projectId: 'habister-dev',
    storageBucket: 'habister-dev.firebasestorage.app',
    iosBundleId: 'com.example.habitFlutterApp.extension',
  );
}
